Integrate fire hazard API calls
CrunchyData/spatial-suite-demo-webapp pull request #29
Opened 2019-11-08 20:35 UTC by xenophenes

2019-11-11 23:19 UTC, jmezzacappa requested changes

2019-11-11 23:19 UTC, jmezzacappa commented on src/views/Categories/components/EditForm/index.jsx
> +    const fireHazardStore = useFireHazardStore(parcelId, fireHazardValue);
Hook functions (`useFireHazardStore`, in this case) need to be called on every render. `fireHazardStore` will need to be declared outside of this handler function.

2019-11-11 23:19 UTC, jmezzacappa commented on src/views/Categories/components/EditForm/index.jsx
> +    fireHazardStore.submit();
We shouldn't submit every time the user selects a new value. This should only happen when the user clicks the "save" button.

2019-11-11 23:19 UTC, jmezzacappa commented on src/views/Categories/components/EditForm/index.jsx
> +          value={isFireHazardStr ? 'Yes' : 'No'}
`isFireHazardStr` is already `'Yes'` or  `'No'`, so no need for the ternary operator here. (In fact, `'No'` is truthy since it's a non-empty string :) So this might not work as expected)
```suggestion
          value={isFireHazardStr}
```

2019-11-12 18:01 UTC, xenophenes commented on src/views/Categories/components/EditForm/index.jsx
> +    fireHazardStore.submit();
I was wondering that. Is there any purpose of having the handler here? If the value is being updated automatically (`value={isFireHazardStr}`), and `fireHazardStore.submit` doesn't need to be run until the Save button is pressed, it seems like `handleFireHazardChange` could be removed entirely. Let me know if that seems correct.

2019-11-12 18:09 UTC, xenophenes commented on src/views/Categories/components/EditForm/index.jsx
> +          value={isFireHazardStr ? 'Yes' : 'No'}
Leftover from when `isFireHazardStr` was still boolean - changed!

2019-11-12 23:38 UTC, jmezzacappa approved these changes

2019-11-12 23:38 UTC, jmezzacappa commented on src/api/index.js
> +     * Sends an API request to set the firehazard status before returning the updated value
```suggestion
     * Sends an API request to set the firehazard status
```

2019-11-12 23:42 UTC, merged