Views: Add Notifier view
CrunchyData/spatial-suite-demo-webapp pull request #8
Opened 2019-10-31 21:30 UTC by xenophenes

- Add 'FormHeading' component
- Add placeholder content corresponding to wireframe
- TODO: Integrate search & notify forms with API
- TODO: Add appropriate CSS/styles

2019-10-31 22:16 UTC, jmezzacappa requested changes
Looks good!
My only request is to update the JSDoc comments that were copied over from the `Categories` view, to make it easier for other developers.

2019-10-31 23:54 UTC, xenophenes commented
@jmezzacappa Hm, I'm looking through the added pages under `/Notifier/` and am not seeing any inaccurate comments. Is it just the main `/Notifier/index.jsx` file that you were thinking could use the clarification? I do see this line:

```
// TODO: Send parcel updates to backend
``` 

which I did rephrase slightly to:

```
// TODO: Send notification about selected parcels to backend
```

Let me know if you had anything specific in mind & I'm happy to update further!

2019-11-01 13:42 UTC, jmezzacappa commented on src/views/Notifier/components/NotifyForm/index.jsx
> + * Form for editing a parcel's risk
This form is not used for editing a parcel's risk. Its purpose is to search for surrounding parcels within a specified radius to be notified.

2019-11-01 22:29 UTC, jmezzacappa approved these changes

2019-11-01 22:29 UTC, merged